-- ============================================================
-- Portal Saúde RH
-- Banco de dados: PostgreSQL
-- Script de criação do banco de dados
-- ============================================================

-- ============================================================
-- Tabela: usuario
-- ============================================================

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    matricula VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- Tabela: categoria
-- ============================================================

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    descricao VARCHAR(255),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- Tabela: solicitacao
-- ============================================================

CREATE TABLE solicitacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocolo VARCHAR(255) NOT NULL UNIQUE,
    usuario_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    descricao TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    data_abertura TIMESTAMP NOT NULL,

    CONSTRAINT fk_solicitacao_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id),

    CONSTRAINT fk_solicitacao_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id)
);

-- ============================================================
-- Tabela: historico_solicitacao
-- ============================================================

CREATE TABLE historico_solicitacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_id BIGINT NOT NULL,
    usuario_id BIGINT,
    data_hora TIMESTAMP NOT NULL,
    acao VARCHAR(255) NOT NULL,
    status_anterior VARCHAR(255),
    novo_status VARCHAR(255),
    observacao TEXT,

    CONSTRAINT fk_historico_solicitacao
        FOREIGN KEY (solicitacao_id)
        REFERENCES solicitacao(id),

    CONSTRAINT fk_historico_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
);

-- ============================================================
-- Índices para facilitar consultas
-- ============================================================

CREATE INDEX idx_solicitacao_usuario
    ON solicitacao(usuario_id);

CREATE INDEX idx_solicitacao_categoria
    ON solicitacao(categoria_id);

CREATE INDEX idx_historico_solicitacao
    ON historico_solicitacao(solicitacao_id);

CREATE INDEX idx_historico_usuario
    ON historico_solicitacao(usuario_id);